name: Go

on:
  push:
    branches: [ backend,feature/workflow]
  pull_request:
    branches: [ backend ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: backend

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: CD
      run: cd peanut996.im/peanut996.im.go

    - name: Build starter
      run: cd starter && bash go.sh 