name: Go

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: backend

    - name: set-up-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build
      run: |
        cd peanut996.im.go/starter && bash build.sh linux
        cd ../logic && bash build.sh linux
        cd ../login && bash build.sh linux
        cd ../gate && bash build.sh linux
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        ref: backend

    - name: set-up-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build
      run: |
        cd peanut996.im.go/starter && bash build.sh linux
        cd ../logic && bash build.sh linux
        cd ../login && bash build.sh linux
        cd ../gate && bash build.sh linux
    - name: scp-upload
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: ${{ secrets.SOURCE_GO }}
        target: ${{ secrets.TARGET }}
        timeout: ${{ secrets.TIMEOUT }}


    - name: run-services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ${{ secrets.RUNGO }}