name: Go

on:
  push:
    branches: [ backend,feature/workflow]
  pull_request:
    branches: [ backend ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: backend

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build-starter
      run: cd peanut996.im.go/starter && bash go.sh 

    - name: build-logic
      run: cd peanut996.im.go/logic && bash go.sh

    - name: build-login
      run: cd peanut996.im.go/login && bash go.sh  
    
    - name: build-gate
      run: cd peanut996.im.go/gate && bash go.sh  

